### PR TITLE
assorted additional build fixes

### PR DESCRIPTION
**Pull request by dlunev**
additional minor tweaks for non-working compilation + reasonable description of the working build environment in compile.readme

May be it would be better to push above readme to wiki?

### CODE REVIEW

**Comment by AlekseyKostyushko** [comment]
Yan,
about SDV - If you've managed to compile SDV, can you share the knowledge?
We were unable to fix errors (and found your conversation with MSFT about it) which appears inside msft headers. (

**Comment by YanVugenfirer** [comment]
Hi Aleksey,

Unfortunately we didn't manage to compile it completely and we are working
with MS to fix those issues. But we still must have the log, even with
errors.

Best regards,
Yan.

On Mon, Mar 14, 2016 at 3:50 PM, AlekseyKostyushko <notifications@github.com

**Comment by AlekseyKostyushko** [comment]
submitted change to wiki page
https://github.com/YanVugenfirer/kvm-guest-drivers-windows/wiki/Building%20the%20drivers

Is env var name ok? (_BUILD_DISABLE_SDV)

**Comment by YanVugenfirer** [comment]
Yes, it is OK.

Thanks for a wiki.

Best regards,
Yan.

**Comment by dlunev** [comment]
ping

**Comment by AlekseyKostyushko** [comment]
ping

**Comment by YanVugenfirer** [comment]
Applied, except for the SDV part.

If you want to disable SDV, please introduce environment variable as
discussed.

Thanks,
Yan.

On Mon, Apr 4, 2016 at 4:14 PM, AlekseyKostyushko <notifications@github.com>
wrote:

> ping
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/YanVugenfirer/kvm-guest-drivers-windows/pull/56#issuecomment-205292190>
>



-- 
-----------------------------------------------------------------------
Daynix Computing LTD
Yan Vugenfirer, CEO
Email: yan@daynix.com
Phone (Israel): +972-54-4758084
Phone (USA): +1-7204776716
Phone (UK): +44-2070482938
Web: www.daynix.com

**Comment by dlunev** [comment]
Yan, pls see latest submission here, specifically commit ee81ae724ff6cd68fc4d045e5e0f9ac8d96b7a32

vioscsi, viostor, netkvm: option to disable SDV
check if _BUILD_DISABLE_SDV env variable is set to bypass SDV
added build_AllNoSdv.bat to set it before calling buildAll.bat

Signed-off-by: Alexey V. Kostyushko <aleksko@virtuozzo.com>
Signed-off-by: Denis V. Lunev <den@openvz.org>

it has all infrastructure inside!

**Comment by YanVugenfirer** [comment]
Hi Denis,

Sorry, somehow I missed it.

Will be applied soon.

Best regards,
Yan.

On Tue, Apr 5, 2016 at 12:24 PM, dlunev <notifications@github.com> wrote:

> Yan, pls see latest submission here, specifically commit ee81ae7
> <https://github.com/YanVugenfirer/kvm-guest-drivers-windows/commit/ee81ae724ff6cd68fc4d045e5e0f9ac8d96b7a32>
>
> vioscsi, viostor, netkvm: option to disable SDV
> check if _BUILD_DISABLE_SDV env variable is set to bypass SDV
> added build_AllNoSdv.bat to set it before calling buildAll.bat
>
> Signed-off-by: Alexey V. Kostyushko aleksko@virtuozzo.com
> Signed-off-by: Denis V. Lunev den@openvz.org
>
> it has all infrastructure inside!
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/YanVugenfirer/kvm-guest-drivers-windows/pull/56#issuecomment-205728017>
>



-- 
-----------------------------------------------------------------------
Daynix Computing LTD
Yan Vugenfirer, CEO
Email: yan@daynix.com
Phone (Israel): +972-54-4758084
Phone (USA): +1-7204776716
Phone (UK): +44-2070482938
Web: www.daynix.com

**Comment by vrozenfe** [comment]
We applied the entire series (all four commits ) on master:
6e3f56adfc84f7fdb1da216c5f8fd52bd2743996 vioscsi, viostor, netkvm: option to disable SDV
d1a287cbb4f111b51ddf62183dd8e03524af0e86 full clean: clean pvpanic and vioscsi also
a7b3e8294294844433582660d25e1a1e9d551f48 NetKVM: drop missed warning.h from build
d0c49bc3450cd28c93f2868f7eae388fb8c182f8 NetKVM build fixes

but only first three on stable:
bfc9b6acba2367b5e8a5fb13ee0df071bd864d4a full clean: clean pvpanic and vioscsi also
e8acf8394a92c0929929f1ce1a5380a5ed1a55a8 NetKVM: drop missed warning.h from build
1878d80f6fa44042ae2be693a5fa01211b546251 NetKVM build fixes
  
The reason for rejecting  
6e3f56adfc84f7fdb1da216c5f8fd52bd2743996 on stable is simple - for builds on production brunch we have to run SDV unconditionally.

Thanks and best regards,
Vadim.

**Comment by dlunev** [comment]
I do not follow the problem with master branch. SDV checks are run by default. We have added the handle to disable them. Why to commit? Surely checks will run until someone will _specifically_ turn that handle off.

**Comment by YanVugenfirer** [comment]
Somehow there is a mess with github messaging system.

To summarise - the commit was applied.

Thanks!

**Comment by dlunev** [comment]
thank you too.

**Comment by dlunev** [comment]
can we have last commit merged to the 'stable' branch as well? SDV is on by default thus your build system will not be affected.

**Comment by YanVugenfirer** [comment]
OK. From my side. Vadim?


On Wed, Apr 6, 2016 at 11:54 AM, dlunev <notifications@github.com> wrote:

> can we have last commit merged to the 'stable' branch as well? SDV is on
> by default thus your build system will not be affected.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/YanVugenfirer/kvm-guest-drivers-windows/pull/56#issuecomment-206230833>
>



-- 
-----------------------------------------------------------------------
Daynix Computing LTD
Yan Vugenfirer, CEO
Email: yan@daynix.com
Phone (Israel): +972-54-4758084
Phone (USA): +1-7204776716
Phone (UK): +44-2070482938
Web: www.daynix.com

**Comment by vrozenfe** [comment]
Applied on stable, even though I don't understand what can be the use case for this patch on production brunch. I will be really glad, if somebody can explain it to me.

Best regards,
Vadim.

**Comment by AlekseyKostyushko** [comment]
Currently SDV generates errors, so for our build system we need a way to disable SDV checks to have good logs and exit codes.

**Comment by vrozenfe** [comment]
With all my respect to the work you guys have commuted so far, do we really need such kind of adjustments? Don't get me wrong, is is not about the latest commit, it is mostly a generic question. 
What should we do if one day someone, who uses mingw instead of WDK and VS for building virtio-win will submit her own patches? 
As I said before, it is a generic question. We should come up with a good understanding of what we should expect to see committed into the branch "stable".

Vadim.

**Comment by dlunev** [comment]
The problem is that build with SDV enabled generates error and thus the build is not passed with success exit code. Thus our build system fails. This looks MS bug which stays here for a long.

This is the problem we are trying to address here. Sorry, if this is not clearly expressed in the commit message.

**Pull request closed without merging**
